version: '3.7'

services:
  nodey:
    container_name: boss
    command: yarn run start-proxy
    build: .
    volumes:
      - ".:/home/node"
    ports:
      - 42001:4200
    environment:
      CHOKIDAR_USEPOLLING: 'true'
